[package]
name = "wnucore-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_cmd = "2.0.17"
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
crossterm = "0.29.0"
tempfile = "3.20.0"
